# Generated by Django 2.0.5 on 2018-06-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('emp_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
